# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sam/Software/MaxSubArray/MaxSubArray

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sam/Software/MaxSubArray/MaxSubArray

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam/Software/MaxSubArray/MaxSubArray/CMakeFiles /home/sam/Software/MaxSubArray/MaxSubArray/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam/Software/MaxSubArray/MaxSubArray/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run.out

# Build rule for target.
run.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run.out
.PHONY : run.out

# fast build rule for target.
run.out/fast:
	$(MAKE) -f CMakeFiles/run.out.dir/build.make CMakeFiles/run.out.dir/build
.PHONY : run.out/fast

Run.o: Run.cpp.o
.PHONY : Run.o

# target to build an object file
Run.cpp.o:
	$(MAKE) -f CMakeFiles/run.out.dir/build.make CMakeFiles/run.out.dir/Run.cpp.o
.PHONY : Run.cpp.o

Run.i: Run.cpp.i
.PHONY : Run.i

# target to preprocess a source file
Run.cpp.i:
	$(MAKE) -f CMakeFiles/run.out.dir/build.make CMakeFiles/run.out.dir/Run.cpp.i
.PHONY : Run.cpp.i

Run.s: Run.cpp.s
.PHONY : Run.s

# target to generate assembly for a file
Run.cpp.s:
	$(MAKE) -f CMakeFiles/run.out.dir/build.make CMakeFiles/run.out.dir/Run.cpp.s
.PHONY : Run.cpp.s

ex_MaxSubArray.o: ex_MaxSubArray.cpp.o
.PHONY : ex_MaxSubArray.o

# target to build an object file
ex_MaxSubArray.cpp.o:
	$(MAKE) -f CMakeFiles/run.out.dir/build.make CMakeFiles/run.out.dir/ex_MaxSubArray.cpp.o
.PHONY : ex_MaxSubArray.cpp.o

ex_MaxSubArray.i: ex_MaxSubArray.cpp.i
.PHONY : ex_MaxSubArray.i

# target to preprocess a source file
ex_MaxSubArray.cpp.i:
	$(MAKE) -f CMakeFiles/run.out.dir/build.make CMakeFiles/run.out.dir/ex_MaxSubArray.cpp.i
.PHONY : ex_MaxSubArray.cpp.i

ex_MaxSubArray.s: ex_MaxSubArray.cpp.s
.PHONY : ex_MaxSubArray.s

# target to generate assembly for a file
ex_MaxSubArray.cpp.s:
	$(MAKE) -f CMakeFiles/run.out.dir/build.make CMakeFiles/run.out.dir/ex_MaxSubArray.cpp.s
.PHONY : ex_MaxSubArray.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run.out"
	@echo "... Run.o"
	@echo "... Run.i"
	@echo "... Run.s"
	@echo "... ex_MaxSubArray.o"
	@echo "... ex_MaxSubArray.i"
	@echo "... ex_MaxSubArray.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

